apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xzk6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-xzk6@sha256:c00a34117b39a72d6327e742824cf392dbccaceb00c0c3e9507e3a2f772851c3
        name: my-nodejs
        resources: {}
status: {}
